spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.141.221:3306/poesy?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: db
    password: 123456
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
  #静态文件映射
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  #解决中文乱码
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
#Spring Boot工程嵌入的tomcat限制了请求的文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml