spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.141.221:3306/poesy?characterEncoding=utf8&useSSL=true
    name: 'db'
    type: com.alibaba.druid.pool.DruidDataSource
    password: '123456'
  #静态文件映射
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  #解决中文乱码
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true